apiVersion: storage.gridscale.m.platformrelay.io/v1alpha1
kind: Clone
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/clone
  labels:
    testing.upbound.io/example-name: storage-clone-john
  name: storage-clone-john
  namespace: crossplane-system
spec:
  forProvider:
    name: john's storage clone
    sourceStorageId: ${gridscale_storage.storage-clone-john.id}
    timeouts:
    - create: 10m

---

apiVersion: gridscale.gridscale.m.platformrelay.io/v1alpha1
kind: Storage
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/clone
  labels:
    testing.upbound.io/example-name: storage-john
  name: storage-john
  namespace: crossplane-system
spec:
  forProvider:
    capacity: 10
    name: john's storage
    storageType: storage_high
    timeouts:
    - create: 10m
