//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImport) DeepCopyInto(out *ApplicationImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImport.
func (in *ApplicationImport) DeepCopy() *ApplicationImport {
	if in == nil {
		return nil
	}
	out := new(ApplicationImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportInitParameters) DeepCopyInto(out *ApplicationImportInitParameters) {
	*out = *in
	if in.ImportUniqueHash != nil {
		in, out := &in.ImportUniqueHash, &out.ImportUniqueHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportInitParameters.
func (in *ApplicationImportInitParameters) DeepCopy() *ApplicationImportInitParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportList) DeepCopyInto(out *ApplicationImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportList.
func (in *ApplicationImportList) DeepCopy() *ApplicationImportList {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportObservation) DeepCopyInto(out *ApplicationImportObservation) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.ChangeTime != nil {
		in, out := &in.ChangeTime, &out.ChangeTime
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImportUniqueHash != nil {
		in, out := &in.ImportUniqueHash, &out.ImportUniqueHash
		*out = new(string)
		**out = **in
	}
	if in.IsApplicationOwner != nil {
		in, out := &in.IsApplicationOwner, &out.IsApplicationOwner
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishGlobal != nil {
		in, out := &in.IsPublishGlobal, &out.IsPublishGlobal
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishGlobalRequested != nil {
		in, out := &in.IsPublishGlobalRequested, &out.IsPublishGlobalRequested
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishRequested != nil {
		in, out := &in.IsPublishRequested, &out.IsPublishRequested
		*out = new(bool)
		**out = **in
	}
	if in.IsPublished != nil {
		in, out := &in.IsPublished, &out.IsPublished
		*out = new(bool)
		**out = **in
	}
	if in.MetaAdvices != nil {
		in, out := &in.MetaAdvices, &out.MetaAdvices
		*out = new(string)
		**out = **in
	}
	if in.MetaAuthor != nil {
		in, out := &in.MetaAuthor, &out.MetaAuthor
		*out = new(string)
		**out = **in
	}
	if in.MetaComponents != nil {
		in, out := &in.MetaComponents, &out.MetaComponents
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetaFeatures != nil {
		in, out := &in.MetaFeatures, &out.MetaFeatures
		*out = new(string)
		**out = **in
	}
	if in.MetaHints != nil {
		in, out := &in.MetaHints, &out.MetaHints
		*out = new(string)
		**out = **in
	}
	if in.MetaIcon != nil {
		in, out := &in.MetaIcon, &out.MetaIcon
		*out = new(string)
		**out = **in
	}
	if in.MetaLicense != nil {
		in, out := &in.MetaLicense, &out.MetaLicense
		*out = new(string)
		**out = **in
	}
	if in.MetaOs != nil {
		in, out := &in.MetaOs, &out.MetaOs
		*out = new(string)
		**out = **in
	}
	if in.MetaOverview != nil {
		in, out := &in.MetaOverview, &out.MetaOverview
		*out = new(string)
		**out = **in
	}
	if in.MetaTermsOfUse != nil {
		in, out := &in.MetaTermsOfUse, &out.MetaTermsOfUse
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectStoragePath != nil {
		in, out := &in.ObjectStoragePath, &out.ObjectStoragePath
		*out = new(string)
		**out = **in
	}
	if in.PublishGlobalRequestedDate != nil {
		in, out := &in.PublishGlobalRequestedDate, &out.PublishGlobalRequestedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishRequestedDate != nil {
		in, out := &in.PublishRequestedDate, &out.PublishRequestedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishedDate != nil {
		in, out := &in.PublishedDate, &out.PublishedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishedGlobalDate != nil {
		in, out := &in.PublishedGlobalDate, &out.PublishedGlobalDate
		*out = new(string)
		**out = **in
	}
	if in.SetupCores != nil {
		in, out := &in.SetupCores, &out.SetupCores
		*out = new(float64)
		**out = **in
	}
	if in.SetupMemory != nil {
		in, out := &in.SetupMemory, &out.SetupMemory
		*out = new(float64)
		**out = **in
	}
	if in.SetupStorageCapacity != nil {
		in, out := &in.SetupStorageCapacity, &out.SetupStorageCapacity
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UniqueHash != nil {
		in, out := &in.UniqueHash, &out.UniqueHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportObservation.
func (in *ApplicationImportObservation) DeepCopy() *ApplicationImportObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportParameters) DeepCopyInto(out *ApplicationImportParameters) {
	*out = *in
	if in.ImportUniqueHash != nil {
		in, out := &in.ImportUniqueHash, &out.ImportUniqueHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportParameters.
func (in *ApplicationImportParameters) DeepCopy() *ApplicationImportParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportSpec) DeepCopyInto(out *ApplicationImportSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportSpec.
func (in *ApplicationImportSpec) DeepCopy() *ApplicationImportSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationImportStatus) DeepCopyInto(out *ApplicationImportStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationImportStatus.
func (in *ApplicationImportStatus) DeepCopy() *ApplicationImportStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInitParameters) DeepCopyInto(out *ApplicationInitParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.MetaAdvices != nil {
		in, out := &in.MetaAdvices, &out.MetaAdvices
		*out = new(string)
		**out = **in
	}
	if in.MetaAuthor != nil {
		in, out := &in.MetaAuthor, &out.MetaAuthor
		*out = new(string)
		**out = **in
	}
	if in.MetaComponents != nil {
		in, out := &in.MetaComponents, &out.MetaComponents
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetaFeatures != nil {
		in, out := &in.MetaFeatures, &out.MetaFeatures
		*out = new(string)
		**out = **in
	}
	if in.MetaHints != nil {
		in, out := &in.MetaHints, &out.MetaHints
		*out = new(string)
		**out = **in
	}
	if in.MetaIcon != nil {
		in, out := &in.MetaIcon, &out.MetaIcon
		*out = new(string)
		**out = **in
	}
	if in.MetaLicense != nil {
		in, out := &in.MetaLicense, &out.MetaLicense
		*out = new(string)
		**out = **in
	}
	if in.MetaOs != nil {
		in, out := &in.MetaOs, &out.MetaOs
		*out = new(string)
		**out = **in
	}
	if in.MetaOverview != nil {
		in, out := &in.MetaOverview, &out.MetaOverview
		*out = new(string)
		**out = **in
	}
	if in.MetaTermsOfUse != nil {
		in, out := &in.MetaTermsOfUse, &out.MetaTermsOfUse
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectStoragePath != nil {
		in, out := &in.ObjectStoragePath, &out.ObjectStoragePath
		*out = new(string)
		**out = **in
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(bool)
		**out = **in
	}
	if in.SetupCores != nil {
		in, out := &in.SetupCores, &out.SetupCores
		*out = new(float64)
		**out = **in
	}
	if in.SetupMemory != nil {
		in, out := &in.SetupMemory, &out.SetupMemory
		*out = new(float64)
		**out = **in
	}
	if in.SetupStorageCapacity != nil {
		in, out := &in.SetupStorageCapacity, &out.SetupStorageCapacity
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInitParameters.
func (in *ApplicationInitParameters) DeepCopy() *ApplicationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationObservation) DeepCopyInto(out *ApplicationObservation) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.ChangeTime != nil {
		in, out := &in.ChangeTime, &out.ChangeTime
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsApplicationOwner != nil {
		in, out := &in.IsApplicationOwner, &out.IsApplicationOwner
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishGlobal != nil {
		in, out := &in.IsPublishGlobal, &out.IsPublishGlobal
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishGlobalRequested != nil {
		in, out := &in.IsPublishGlobalRequested, &out.IsPublishGlobalRequested
		*out = new(bool)
		**out = **in
	}
	if in.IsPublishRequested != nil {
		in, out := &in.IsPublishRequested, &out.IsPublishRequested
		*out = new(bool)
		**out = **in
	}
	if in.IsPublished != nil {
		in, out := &in.IsPublished, &out.IsPublished
		*out = new(bool)
		**out = **in
	}
	if in.MetaAdvices != nil {
		in, out := &in.MetaAdvices, &out.MetaAdvices
		*out = new(string)
		**out = **in
	}
	if in.MetaAuthor != nil {
		in, out := &in.MetaAuthor, &out.MetaAuthor
		*out = new(string)
		**out = **in
	}
	if in.MetaComponents != nil {
		in, out := &in.MetaComponents, &out.MetaComponents
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetaFeatures != nil {
		in, out := &in.MetaFeatures, &out.MetaFeatures
		*out = new(string)
		**out = **in
	}
	if in.MetaHints != nil {
		in, out := &in.MetaHints, &out.MetaHints
		*out = new(string)
		**out = **in
	}
	if in.MetaIcon != nil {
		in, out := &in.MetaIcon, &out.MetaIcon
		*out = new(string)
		**out = **in
	}
	if in.MetaLicense != nil {
		in, out := &in.MetaLicense, &out.MetaLicense
		*out = new(string)
		**out = **in
	}
	if in.MetaOs != nil {
		in, out := &in.MetaOs, &out.MetaOs
		*out = new(string)
		**out = **in
	}
	if in.MetaOverview != nil {
		in, out := &in.MetaOverview, &out.MetaOverview
		*out = new(string)
		**out = **in
	}
	if in.MetaTermsOfUse != nil {
		in, out := &in.MetaTermsOfUse, &out.MetaTermsOfUse
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectStoragePath != nil {
		in, out := &in.ObjectStoragePath, &out.ObjectStoragePath
		*out = new(string)
		**out = **in
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(bool)
		**out = **in
	}
	if in.PublishGlobalRequestedDate != nil {
		in, out := &in.PublishGlobalRequestedDate, &out.PublishGlobalRequestedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishRequestedDate != nil {
		in, out := &in.PublishRequestedDate, &out.PublishRequestedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishedDate != nil {
		in, out := &in.PublishedDate, &out.PublishedDate
		*out = new(string)
		**out = **in
	}
	if in.PublishedGlobalDate != nil {
		in, out := &in.PublishedGlobalDate, &out.PublishedGlobalDate
		*out = new(string)
		**out = **in
	}
	if in.SetupCores != nil {
		in, out := &in.SetupCores, &out.SetupCores
		*out = new(float64)
		**out = **in
	}
	if in.SetupMemory != nil {
		in, out := &in.SetupMemory, &out.SetupMemory
		*out = new(float64)
		**out = **in
	}
	if in.SetupStorageCapacity != nil {
		in, out := &in.SetupStorageCapacity, &out.SetupStorageCapacity
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UniqueHash != nil {
		in, out := &in.UniqueHash, &out.UniqueHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationObservation.
func (in *ApplicationObservation) DeepCopy() *ApplicationObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationParameters) DeepCopyInto(out *ApplicationParameters) {
	*out = *in
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = new(string)
		**out = **in
	}
	if in.MetaAdvices != nil {
		in, out := &in.MetaAdvices, &out.MetaAdvices
		*out = new(string)
		**out = **in
	}
	if in.MetaAuthor != nil {
		in, out := &in.MetaAuthor, &out.MetaAuthor
		*out = new(string)
		**out = **in
	}
	if in.MetaComponents != nil {
		in, out := &in.MetaComponents, &out.MetaComponents
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetaFeatures != nil {
		in, out := &in.MetaFeatures, &out.MetaFeatures
		*out = new(string)
		**out = **in
	}
	if in.MetaHints != nil {
		in, out := &in.MetaHints, &out.MetaHints
		*out = new(string)
		**out = **in
	}
	if in.MetaIcon != nil {
		in, out := &in.MetaIcon, &out.MetaIcon
		*out = new(string)
		**out = **in
	}
	if in.MetaLicense != nil {
		in, out := &in.MetaLicense, &out.MetaLicense
		*out = new(string)
		**out = **in
	}
	if in.MetaOs != nil {
		in, out := &in.MetaOs, &out.MetaOs
		*out = new(string)
		**out = **in
	}
	if in.MetaOverview != nil {
		in, out := &in.MetaOverview, &out.MetaOverview
		*out = new(string)
		**out = **in
	}
	if in.MetaTermsOfUse != nil {
		in, out := &in.MetaTermsOfUse, &out.MetaTermsOfUse
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectStoragePath != nil {
		in, out := &in.ObjectStoragePath, &out.ObjectStoragePath
		*out = new(string)
		**out = **in
	}
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(bool)
		**out = **in
	}
	if in.SetupCores != nil {
		in, out := &in.SetupCores, &out.SetupCores
		*out = new(float64)
		**out = **in
	}
	if in.SetupMemory != nil {
		in, out := &in.SetupMemory, &out.SetupMemory
		*out = new(float64)
		**out = **in
	}
	if in.SetupStorageCapacity != nil {
		in, out := &in.SetupStorageCapacity, &out.SetupStorageCapacity
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationParameters.
func (in *ApplicationParameters) DeepCopy() *ApplicationParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}
