apiVersion: paas.gridscale.platformrelay.io/v1alpha1
kind: Securityzone
metadata:
  annotations:
    meta.upbound.io/example-id: paas/v1alpha1/securityzone
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: test
    timeouts:
    - create: 10m
