// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ApplicationImportInitParameters struct {

	// Hash of a specific marketplace application that you want to import
	ImportUniqueHash *string `json:"importUniqueHash,omitempty" tf:"import_unique_hash,omitempty"`
}

type ApplicationImportObservation struct {

	// Category of marketplace application. Accepted values: "CMS", "project management", "Adminpanel", "Collaboration", "Cloud Storage", "Archiving"
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// Defines the date and time of the last object change
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Defines the date and time the object was initially created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Hash of a specific marketplace application that you want to import
	ImportUniqueHash *string `json:"importUniqueHash,omitempty" tf:"import_unique_hash,omitempty"`

	// Whether the you are the owner of application or not
	IsApplicationOwner *bool `json:"isApplicationOwner,omitempty" tf:"is_application_owner,omitempty"`

	// Whether a template is published to other partner or not
	IsPublishGlobal *bool `json:"isPublishGlobal,omitempty" tf:"is_publish_global,omitempty"`

	// Whether a partner wants their tenant template published to other partners
	IsPublishGlobalRequested *bool `json:"isPublishGlobalRequested,omitempty" tf:"is_publish_global_requested,omitempty"`

	// Whether the tenants want their template to be published or not
	IsPublishRequested *bool `json:"isPublishRequested,omitempty" tf:"is_publish_requested,omitempty"`

	// Whether the template is published by the partner to their tenant
	IsPublished *bool `json:"isPublished,omitempty" tf:"is_published,omitempty"`

	MetaAdvices *string `json:"metaAdvices,omitempty" tf:"meta_advices,omitempty"`

	MetaAuthor *string `json:"metaAuthor,omitempty" tf:"meta_author,omitempty"`

	// +listType=set
	MetaComponents []*string `json:"metaComponents,omitempty" tf:"meta_components,omitempty"`

	MetaFeatures *string `json:"metaFeatures,omitempty" tf:"meta_features,omitempty"`

	MetaHints *string `json:"metaHints,omitempty" tf:"meta_hints,omitempty"`

	MetaIcon *string `json:"metaIcon,omitempty" tf:"meta_icon,omitempty"`

	MetaLicense *string `json:"metaLicense,omitempty" tf:"meta_license,omitempty"`

	MetaOs *string `json:"metaOs,omitempty" tf:"meta_os,omitempty"`

	MetaOverview *string `json:"metaOverview,omitempty" tf:"meta_overview,omitempty"`

	MetaTermsOfUse *string `json:"metaTermsOfUse,omitempty" tf:"meta_terms_of_use,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Path to the images for the application, must be in .gz format and started with s3//
	ObjectStoragePath *string `json:"objectStoragePath,omitempty" tf:"object_storage_path,omitempty"`

	// The date when a partner requested their tenants template to be published
	PublishGlobalRequestedDate *string `json:"publishGlobalRequestedDate,omitempty" tf:"publish_global_requested_date,omitempty"`

	// The date when the tenant requested their template to be published
	PublishRequestedDate *string `json:"publishRequestedDate,omitempty" tf:"publish_requested_date,omitempty"`

	// The date when the template is published into other tenant in the same partner
	PublishedDate *string `json:"publishedDate,omitempty" tf:"published_date,omitempty"`

	// The date when a template is published to other partner
	PublishedGlobalDate *string `json:"publishedGlobalDate,omitempty" tf:"published_global_date,omitempty"`

	// Number of server's cores
	SetupCores *float64 `json:"setupCores,omitempty" tf:"setup_cores,omitempty"`

	// The capacity of server's memory in GB
	SetupMemory *float64 `json:"setupMemory,omitempty" tf:"setup_memory,omitempty"`

	// The capacity of server's storage in GB
	SetupStorageCapacity *float64 `json:"setupStorageCapacity,omitempty" tf:"setup_storage_capacity,omitempty"`

	// status indicates the status of the object
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The type of template
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Unique hash to allow user to import the self-created marketplace application
	UniqueHash *string `json:"uniqueHash,omitempty" tf:"unique_hash,omitempty"`
}

type ApplicationImportParameters struct {

	// Hash of a specific marketplace application that you want to import
	// +kubebuilder:validation:Optional
	ImportUniqueHash *string `json:"importUniqueHash,omitempty" tf:"import_unique_hash,omitempty"`
}

// ApplicationImportSpec defines the desired state of ApplicationImport
type ApplicationImportSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ApplicationImportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationImportInitParameters `json:"initProvider,omitempty"`
}

// ApplicationImportStatus defines the observed state of ApplicationImport.
type ApplicationImportStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApplicationImportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ApplicationImport is the Schema for the ApplicationImports API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type ApplicationImport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.importUniqueHash) || (has(self.initProvider) && has(self.initProvider.importUniqueHash))",message="spec.forProvider.importUniqueHash is a required parameter"
	Spec   ApplicationImportSpec   `json:"spec"`
	Status ApplicationImportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationImportList contains a list of ApplicationImports
type ApplicationImportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApplicationImport `json:"items"`
}

// Repository type metadata.
var (
	ApplicationImport_Kind             = "ApplicationImport"
	ApplicationImport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ApplicationImport_Kind}.String()
	ApplicationImport_KindAPIVersion   = ApplicationImport_Kind + "." + CRDGroupVersion.String()
	ApplicationImport_GroupVersionKind = CRDGroupVersion.WithKind(ApplicationImport_Kind)
)

func init() {
	SchemeBuilder.Register(&ApplicationImport{}, &ApplicationImportList{})
}
