// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BackupscheduleInitParameters struct {

	// The status of the schedule active or not.
	// The status of the schedule active or not
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// UUID of the location where your backup is stored.
	// UUID of the location where your backup is stored.
	BackupLocationUUID *string `json:"backupLocationUuid,omitempty" tf:"backup_location_uuid,omitempty"`

	// The amount of Snapshots to keep before overwriting the last created Snapshot (>=1).
	// The amount of storage backups to keep before overwriting the last created backup
	KeepBackups *float64 `json:"keepBackups,omitempty" tf:"keep_backups,omitempty"`

	// UUID of the backup schedule.
	// The human-readable name of the object
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The date and time that the backup schedule will be run.
	// The date and time that the storage backup schedule will be run. Format: "2006-01-02 15:04:05"
	NextRuntime *string `json:"nextRuntime,omitempty" tf:"next_runtime,omitempty"`

	// The interval at which the schedule will run (in minutes, >=60).
	// The interval at which the schedule will run (in minutes)
	RunInterval *float64 `json:"runInterval,omitempty" tf:"run_interval,omitempty"`

	// UUID of the storage that the backup schedule belongs to.
	// UUID of the storage used to create storage backups
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Storage
	StorageUUID *string `json:"storageUuid,omitempty" tf:"storage_uuid,omitempty"`

	// Reference to a Storage in gridscale to populate storageUuid.
	// +kubebuilder:validation:Optional
	StorageUUIDRef *v1.Reference `json:"storageUuidRef,omitempty" tf:"-"`

	// Selector for a Storage in gridscale to populate storageUuid.
	// +kubebuilder:validation:Optional
	StorageUUIDSelector *v1.Selector `json:"storageUuidSelector,omitempty" tf:"-"`
}

type BackupscheduleObservation struct {

	// The status of the schedule active or not.
	// The status of the schedule active or not
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// The human-readable name of backup location. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of backup location. It supports the full UTF-8 character set, with a maximum of 64 characters.
	BackupLocationName *string `json:"backupLocationName,omitempty" tf:"backup_location_name,omitempty"`

	// UUID of the location where your backup is stored.
	// UUID of the location where your backup is stored.
	BackupLocationUUID *string `json:"backupLocationUuid,omitempty" tf:"backup_location_uuid,omitempty"`

	// The date and time of the last backup schedule change.
	// Defines the date and time of the last object change
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// The date and time the backup schedule was initially created.
	// Defines the date and time the object was initially created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The UUID of the backup schedule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The amount of Snapshots to keep before overwriting the last created Snapshot (>=1).
	// The amount of storage backups to keep before overwriting the last created backup
	KeepBackups *float64 `json:"keepBackups,omitempty" tf:"keep_backups,omitempty"`

	// UUID of the backup schedule.
	// The human-readable name of the object
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The date and time that the backup schedule will be run.
	// The date and time that the storage backup schedule will be run. Format: "2006-01-02 15:04:05"
	NextRuntime *string `json:"nextRuntime,omitempty" tf:"next_runtime,omitempty"`

	// The date and time that the backup schedule will be run. This date and time is computed by gridscale's server.
	// The date and time that the storage backup schedule will be run. This date and time is computed by gridscale's server.
	NextRuntimeComputed *string `json:"nextRuntimeComputed,omitempty" tf:"next_runtime_computed,omitempty"`

	// The interval at which the schedule will run (in minutes, >=60).
	// The interval at which the schedule will run (in minutes)
	RunInterval *float64 `json:"runInterval,omitempty" tf:"run_interval,omitempty"`

	// The status of the backup schedule.
	// Status indicates the status of the object
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Related backups.
	// Related backups
	StorageBackups []StorageBackupsObservation `json:"storageBackups,omitempty" tf:"storage_backups,omitempty"`

	// UUID of the storage that the backup schedule belongs to.
	// UUID of the storage used to create storage backups
	StorageUUID *string `json:"storageUuid,omitempty" tf:"storage_uuid,omitempty"`
}

type BackupscheduleParameters struct {

	// The status of the schedule active or not.
	// The status of the schedule active or not
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// UUID of the location where your backup is stored.
	// UUID of the location where your backup is stored.
	// +kubebuilder:validation:Optional
	BackupLocationUUID *string `json:"backupLocationUuid,omitempty" tf:"backup_location_uuid,omitempty"`

	// The amount of Snapshots to keep before overwriting the last created Snapshot (>=1).
	// The amount of storage backups to keep before overwriting the last created backup
	// +kubebuilder:validation:Optional
	KeepBackups *float64 `json:"keepBackups,omitempty" tf:"keep_backups,omitempty"`

	// UUID of the backup schedule.
	// The human-readable name of the object
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The date and time that the backup schedule will be run.
	// The date and time that the storage backup schedule will be run. Format: "2006-01-02 15:04:05"
	// +kubebuilder:validation:Optional
	NextRuntime *string `json:"nextRuntime,omitempty" tf:"next_runtime,omitempty"`

	// The interval at which the schedule will run (in minutes, >=60).
	// The interval at which the schedule will run (in minutes)
	// +kubebuilder:validation:Optional
	RunInterval *float64 `json:"runInterval,omitempty" tf:"run_interval,omitempty"`

	// UUID of the storage that the backup schedule belongs to.
	// UUID of the storage used to create storage backups
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Storage
	// +kubebuilder:validation:Optional
	StorageUUID *string `json:"storageUuid,omitempty" tf:"storage_uuid,omitempty"`

	// Reference to a Storage in gridscale to populate storageUuid.
	// +kubebuilder:validation:Optional
	StorageUUIDRef *v1.Reference `json:"storageUuidRef,omitempty" tf:"-"`

	// Selector for a Storage in gridscale to populate storageUuid.
	// +kubebuilder:validation:Optional
	StorageUUIDSelector *v1.Selector `json:"storageUuidSelector,omitempty" tf:"-"`
}

type StorageBackupsInitParameters struct {
}

type StorageBackupsObservation struct {

	// The date and time the backup schedule was initially created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// UUID of the backup schedule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// UUID of the backup.
	ObjectUUID *string `json:"objectUuid,omitempty" tf:"object_uuid,omitempty"`
}

type StorageBackupsParameters struct {
}

// BackupscheduleSpec defines the desired state of Backupschedule
type BackupscheduleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BackupscheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BackupscheduleInitParameters `json:"initProvider,omitempty"`
}

// BackupscheduleStatus defines the observed state of Backupschedule.
type BackupscheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BackupscheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Backupschedule is the Schema for the Backupschedules API. Manages a storage backup schedule.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gridscale}
type Backupschedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.active) || (has(self.initProvider) && has(self.initProvider.active))",message="spec.forProvider.active is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keepBackups) || (has(self.initProvider) && has(self.initProvider.keepBackups))",message="spec.forProvider.keepBackups is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nextRuntime) || (has(self.initProvider) && has(self.initProvider.nextRuntime))",message="spec.forProvider.nextRuntime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runInterval) || (has(self.initProvider) && has(self.initProvider.runInterval))",message="spec.forProvider.runInterval is a required parameter"
	Spec   BackupscheduleSpec   `json:"spec"`
	Status BackupscheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupscheduleList contains a list of Backupschedules
type BackupscheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Backupschedule `json:"items"`
}

// Repository type metadata.
var (
	Backupschedule_Kind             = "Backupschedule"
	Backupschedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Backupschedule_Kind}.String()
	Backupschedule_KindAPIVersion   = Backupschedule_Kind + "." + CRDGroupVersion.String()
	Backupschedule_GroupVersionKind = CRDGroupVersion.WithKind(Backupschedule_Kind)
)

func init() {
	SchemeBuilder.Register(&Backupschedule{}, &BackupscheduleList{})
}
