// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MySQLInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The mysql instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MySQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// mysql parameter: Binary Logging Format. Default: "ROW".
	// Binary Logging Format.
	MySQLBinlogFormat *string `json:"mysqlBinlogFormat,omitempty" tf:"mysql_binlog_format,omitempty"`

	// mysql parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	MySQLDefaultTimeZone *string `json:"mysqlDefaultTimeZone,omitempty" tf:"mysql_default_time_zone,omitempty"`

	// mysql parameter: Binary Logging. Default: false.
	// Binary Logging.
	MySQLLogBin *bool `json:"mysqlLogBin,omitempty" tf:"mysql_log_bin,omitempty"`

	// mysql parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLMaxAllowedPacket *string `json:"mysqlMaxAllowedPacket,omitempty" tf:"mysql_max_allowed_packet,omitempty"`

	// mysql parameter: Max Connections. Default: 4000.
	// Max Connections.
	MySQLMaxConnections *float64 `json:"mysqlMaxConnections,omitempty" tf:"mysql_max_connections,omitempty"`

	// mysql parameter: Enable query cache. Default: true.
	// Enable query cache.
	MySQLQueryCache *bool `json:"mysqlQueryCache,omitempty" tf:"mysql_query_cache,omitempty"`

	// mysql parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLQueryCacheLimit *string `json:"mysqlQueryCacheLimit,omitempty" tf:"mysql_query_cache_limit,omitempty"`

	// mysql parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLQueryCacheSize *string `json:"mysqlQueryCacheSize,omitempty" tf:"mysql_query_cache_size,omitempty"`

	// mysql parameter: SQL Mode. Default: "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION".
	// SQL Mode.
	MySQLSQLMode *string `json:"mysqlSqlMode,omitempty" tf:"mysql_sql_mode,omitempty"`

	// mysql parameter: Server Id. Default: 1.
	// Server Id.
	MySQLServerID *float64 `json:"mysqlServerId,omitempty" tf:"mysql_server_id,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of mysql service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MySQL service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The mysql release of this instance. For convenience, please use gscloud to get the list of available mysql service releases.
	// The MySQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MySQL service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MySQL service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type MySQLListenPortInitParameters struct {
}

type MySQLListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type MySQLListenPortParameters struct {
}

type MySQLObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this mysql service accepts connections.
	// The port numbers where this MySQL service accepts connections.
	ListenPort []MySQLListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Maximum CPU core count. The mysql instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MySQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// mysql parameter: Binary Logging Format. Default: "ROW".
	// Binary Logging Format.
	MySQLBinlogFormat *string `json:"mysqlBinlogFormat,omitempty" tf:"mysql_binlog_format,omitempty"`

	// mysql parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	MySQLDefaultTimeZone *string `json:"mysqlDefaultTimeZone,omitempty" tf:"mysql_default_time_zone,omitempty"`

	// mysql parameter: Binary Logging. Default: false.
	// Binary Logging.
	MySQLLogBin *bool `json:"mysqlLogBin,omitempty" tf:"mysql_log_bin,omitempty"`

	// mysql parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLMaxAllowedPacket *string `json:"mysqlMaxAllowedPacket,omitempty" tf:"mysql_max_allowed_packet,omitempty"`

	// mysql parameter: Max Connections. Default: 4000.
	// Max Connections.
	MySQLMaxConnections *float64 `json:"mysqlMaxConnections,omitempty" tf:"mysql_max_connections,omitempty"`

	// mysql parameter: Enable query cache. Default: true.
	// Enable query cache.
	MySQLQueryCache *bool `json:"mysqlQueryCache,omitempty" tf:"mysql_query_cache,omitempty"`

	// mysql parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLQueryCacheLimit *string `json:"mysqlQueryCacheLimit,omitempty" tf:"mysql_query_cache_limit,omitempty"`

	// mysql parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MySQLQueryCacheSize *string `json:"mysqlQueryCacheSize,omitempty" tf:"mysql_query_cache_size,omitempty"`

	// mysql parameter: SQL Mode. Default: "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION".
	// SQL Mode.
	MySQLSQLMode *string `json:"mysqlSqlMode,omitempty" tf:"mysql_sql_mode,omitempty"`

	// mysql parameter: Server Id. Default: 1.
	// Server Id.
	MySQLServerID *float64 `json:"mysqlServerId,omitempty" tf:"mysql_server_id,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of mysql service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MySQL service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The mysql release of this instance. For convenience, please use gscloud to get the list of available mysql service releases.
	// The MySQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MySQL service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MySQL service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that mysql service uses.
	// PaaS service template that MySQL service uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of MySQL service.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that MySQL service is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type MySQLParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The mysql instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MySQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	// +kubebuilder:validation:Optional
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// mysql parameter: Binary Logging Format. Default: "ROW".
	// Binary Logging Format.
	// +kubebuilder:validation:Optional
	MySQLBinlogFormat *string `json:"mysqlBinlogFormat,omitempty" tf:"mysql_binlog_format,omitempty"`

	// mysql parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	// +kubebuilder:validation:Optional
	MySQLDefaultTimeZone *string `json:"mysqlDefaultTimeZone,omitempty" tf:"mysql_default_time_zone,omitempty"`

	// mysql parameter: Binary Logging. Default: false.
	// Binary Logging.
	// +kubebuilder:validation:Optional
	MySQLLogBin *bool `json:"mysqlLogBin,omitempty" tf:"mysql_log_bin,omitempty"`

	// mysql parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MySQLMaxAllowedPacket *string `json:"mysqlMaxAllowedPacket,omitempty" tf:"mysql_max_allowed_packet,omitempty"`

	// mysql parameter: Max Connections. Default: 4000.
	// Max Connections.
	// +kubebuilder:validation:Optional
	MySQLMaxConnections *float64 `json:"mysqlMaxConnections,omitempty" tf:"mysql_max_connections,omitempty"`

	// mysql parameter: Enable query cache. Default: true.
	// Enable query cache.
	// +kubebuilder:validation:Optional
	MySQLQueryCache *bool `json:"mysqlQueryCache,omitempty" tf:"mysql_query_cache,omitempty"`

	// mysql parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MySQLQueryCacheLimit *string `json:"mysqlQueryCacheLimit,omitempty" tf:"mysql_query_cache_limit,omitempty"`

	// mysql parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MySQLQueryCacheSize *string `json:"mysqlQueryCacheSize,omitempty" tf:"mysql_query_cache_size,omitempty"`

	// mysql parameter: SQL Mode. Default: "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION".
	// SQL Mode.
	// +kubebuilder:validation:Optional
	MySQLSQLMode *string `json:"mysqlSqlMode,omitempty" tf:"mysql_sql_mode,omitempty"`

	// mysql parameter: Server Id. Default: 1.
	// Server Id.
	// +kubebuilder:validation:Optional
	MySQLServerID *float64 `json:"mysqlServerId,omitempty" tf:"mysql_server_id,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of mysql service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MySQL service.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The mysql release of this instance. For convenience, please use gscloud to get the list of available mysql service releases.
	// The MySQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MySQL service releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MySQL service.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// MySQLSpec defines the desired state of MySQL
type MySQLSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MySQLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MySQLInitParameters `json:"initProvider,omitempty"`
}

// MySQLStatus defines the observed state of MySQL.
type MySQLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MySQLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MySQL is the Schema for the MySQLs API. Manage a MySQL service in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gridscale}
type MySQL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   MySQLSpec   `json:"spec"`
	Status MySQLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MySQLList contains a list of MySQLs
type MySQLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MySQL `json:"items"`
}

// Repository type metadata.
var (
	MySQL_Kind             = "MySQL"
	MySQL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MySQL_Kind}.String()
	MySQL_KindAPIVersion   = MySQL_Kind + "." + CRDGroupVersion.String()
	MySQL_GroupVersionKind = CRDGroupVersion.WithKind(MySQL_Kind)
)

func init() {
	SchemeBuilder.Register(&MySQL{}, &MySQLList{})
}
