// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MariadbInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// MariaDB parameter: Binary Logging Format. Default: "MIXED".
	// Binary Logging Format.
	MariadbBinlogFormat *string `json:"mariadbBinlogFormat,omitempty" tf:"mariadb_binlog_format,omitempty"`

	// MariaDB parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	MariadbDefaultTimeZone *string `json:"mariadbDefaultTimeZone,omitempty" tf:"mariadb_default_time_zone,omitempty"`

	// MariaDB parameter: Binary Logging. Default: false.
	// Binary Logging.
	MariadbLogBin *bool `json:"mariadbLogBin,omitempty" tf:"mariadb_log_bin,omitempty"`

	// MariaDB parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbMaxAllowedPacket *string `json:"mariadbMaxAllowedPacket,omitempty" tf:"mariadb_max_allowed_packet,omitempty"`

	// MariaDB parameter: Max Connections. Default: 4000.
	// Max Connections.
	MariadbMaxConnections *float64 `json:"mariadbMaxConnections,omitempty" tf:"mariadb_max_connections,omitempty"`

	// MariaDB parameter: Enable query cache. Default: true.
	// Enable query cache.
	MariadbQueryCache *bool `json:"mariadbQueryCache,omitempty" tf:"mariadb_query_cache,omitempty"`

	// MariaDB parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbQueryCacheLimit *string `json:"mariadbQueryCacheLimit,omitempty" tf:"mariadb_query_cache_limit,omitempty"`

	// MariaDB parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbQueryCacheSize *string `json:"mariadbQueryCacheSize,omitempty" tf:"mariadb_query_cache_size,omitempty"`

	// MariaDB parameter: SQL Mode. Default: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO".
	// SQL Mode.
	MariadbSQLMode *string `json:"mariadbSqlMode,omitempty" tf:"mariadb_sql_mode,omitempty"`

	// MariaDB parameter: Server Id. Default: 1.
	// Server Id.
	MariadbServerID *float64 `json:"mariadbServerId,omitempty" tf:"mariadb_server_id,omitempty"`

	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of MariaDB service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MariaDB service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MariaDB release of this instance. For convenience, please use gscloud to get the list of available MariaDB service releases.
	// The MariaDB release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MariaDB service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MariaDB service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type MariadbListenPortInitParameters struct {
}

type MariadbListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type MariadbListenPortParameters struct {
}

type MariadbObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this MariaDB service accepts connections.
	// The port numbers where this MariaDB service accepts connections.
	ListenPort []MariadbListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// MariaDB parameter: Binary Logging Format. Default: "MIXED".
	// Binary Logging Format.
	MariadbBinlogFormat *string `json:"mariadbBinlogFormat,omitempty" tf:"mariadb_binlog_format,omitempty"`

	// MariaDB parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	MariadbDefaultTimeZone *string `json:"mariadbDefaultTimeZone,omitempty" tf:"mariadb_default_time_zone,omitempty"`

	// MariaDB parameter: Binary Logging. Default: false.
	// Binary Logging.
	MariadbLogBin *bool `json:"mariadbLogBin,omitempty" tf:"mariadb_log_bin,omitempty"`

	// MariaDB parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbMaxAllowedPacket *string `json:"mariadbMaxAllowedPacket,omitempty" tf:"mariadb_max_allowed_packet,omitempty"`

	// MariaDB parameter: Max Connections. Default: 4000.
	// Max Connections.
	MariadbMaxConnections *float64 `json:"mariadbMaxConnections,omitempty" tf:"mariadb_max_connections,omitempty"`

	// MariaDB parameter: Enable query cache. Default: true.
	// Enable query cache.
	MariadbQueryCache *bool `json:"mariadbQueryCache,omitempty" tf:"mariadb_query_cache,omitempty"`

	// MariaDB parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbQueryCacheLimit *string `json:"mariadbQueryCacheLimit,omitempty" tf:"mariadb_query_cache_limit,omitempty"`

	// MariaDB parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	MariadbQueryCacheSize *string `json:"mariadbQueryCacheSize,omitempty" tf:"mariadb_query_cache_size,omitempty"`

	// MariaDB parameter: SQL Mode. Default: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO".
	// SQL Mode.
	MariadbSQLMode *string `json:"mariadbSqlMode,omitempty" tf:"mariadb_sql_mode,omitempty"`

	// MariaDB parameter: Server Id. Default: 1.
	// Server Id.
	MariadbServerID *float64 `json:"mariadbServerId,omitempty" tf:"mariadb_server_id,omitempty"`

	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of MariaDB service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MariaDB service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MariaDB release of this instance. For convenience, please use gscloud to get the list of available MariaDB service releases.
	// The MariaDB release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MariaDB service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MariaDB service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that MariaDB service uses.
	// PaaS service template that MariaDB service uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of MariaDB service.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that MariaDB service is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type MariadbParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// MariaDB parameter: Binary Logging Format. Default: "MIXED".
	// Binary Logging Format.
	// +kubebuilder:validation:Optional
	MariadbBinlogFormat *string `json:"mariadbBinlogFormat,omitempty" tf:"mariadb_binlog_format,omitempty"`

	// MariaDB parameter: Server Timezone. Default: UTC.
	// Server Timezone.
	// +kubebuilder:validation:Optional
	MariadbDefaultTimeZone *string `json:"mariadbDefaultTimeZone,omitempty" tf:"mariadb_default_time_zone,omitempty"`

	// MariaDB parameter: Binary Logging. Default: false.
	// Binary Logging.
	// +kubebuilder:validation:Optional
	MariadbLogBin *bool `json:"mariadbLogBin,omitempty" tf:"mariadb_log_bin,omitempty"`

	// MariaDB parameter: Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 64M.
	// Max Allowed Packet Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MariadbMaxAllowedPacket *string `json:"mariadbMaxAllowedPacket,omitempty" tf:"mariadb_max_allowed_packet,omitempty"`

	// MariaDB parameter: Max Connections. Default: 4000.
	// Max Connections.
	// +kubebuilder:validation:Optional
	MariadbMaxConnections *float64 `json:"mariadbMaxConnections,omitempty" tf:"mariadb_max_connections,omitempty"`

	// MariaDB parameter: Enable query cache. Default: true.
	// Enable query cache.
	// +kubebuilder:validation:Optional
	MariadbQueryCache *bool `json:"mariadbQueryCache,omitempty" tf:"mariadb_query_cache,omitempty"`

	// MariaDB parameter: Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 1M.
	// Query Cache Limit. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MariadbQueryCacheLimit *string `json:"mariadbQueryCacheLimit,omitempty" tf:"mariadb_query_cache_limit,omitempty"`

	// MariaDB parameter: Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)). Default: 128M.
	// Query Cache Size. Format: xM (where x is an integer, M stands for unit: k(kB), M(MB), G(GB)).
	// +kubebuilder:validation:Optional
	MariadbQueryCacheSize *string `json:"mariadbQueryCacheSize,omitempty" tf:"mariadb_query_cache_size,omitempty"`

	// MariaDB parameter: SQL Mode. Default: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO".
	// SQL Mode.
	// +kubebuilder:validation:Optional
	MariadbSQLMode *string `json:"mariadbSqlMode,omitempty" tf:"mariadb_sql_mode,omitempty"`

	// MariaDB parameter: Server Id. Default: 1.
	// Server Id.
	// +kubebuilder:validation:Optional
	MariadbServerID *float64 `json:"mariadbServerId,omitempty" tf:"mariadb_server_id,omitempty"`

	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The MariaDB instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	// +kubebuilder:validation:Optional
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of MariaDB service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MariaDB service.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MariaDB release of this instance. For convenience, please use gscloud to get the list of available MariaDB service releases.
	// The MariaDB release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MariaDB service releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MariaDB service.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// MariadbSpec defines the desired state of Mariadb
type MariadbSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MariadbParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MariadbInitParameters `json:"initProvider,omitempty"`
}

// MariadbStatus defines the observed state of Mariadb.
type MariadbStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MariadbObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Mariadb is the Schema for the Mariadbs API. Manage a MariaDB service in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gridscale}
type Mariadb struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   MariadbSpec   `json:"spec"`
	Status MariadbStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MariadbList contains a list of Mariadbs
type MariadbList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Mariadb `json:"items"`
}

// Repository type metadata.
var (
	Mariadb_Kind             = "Mariadb"
	Mariadb_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Mariadb_Kind}.String()
	Mariadb_KindAPIVersion   = Mariadb_Kind + "." + CRDGroupVersion.String()
	Mariadb_GroupVersionKind = CRDGroupVersion.WithKind(Mariadb_Kind)
)

func init() {
	SchemeBuilder.Register(&Mariadb{}, &MariadbList{})
}
