// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MemcachedInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of Memcached service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Memcached service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Memcached release of this instance. For convenience, please use gscloud to get the list of available Memcached service releases.
	// The Memcached release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Memcached service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Memcached service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type MemcachedListenPortInitParameters struct {
}

type MemcachedListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type MemcachedListenPortParameters struct {
}

type MemcachedObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this Memcached service accepts connections.
	// The port numbers where this Memcached service accepts connections.
	ListenPort []MemcachedListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of Memcached service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Memcached service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Memcached release of this instance. For convenience, please use gscloud to get the list of available Memcached service releases.
	// The Memcached release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Memcached service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Memcached service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that Memcached service uses.
	// PaaS service template that Memcached service uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of Memcached service.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that Memcached service is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type MemcachedParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The Memcached instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	// +kubebuilder:validation:Optional
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of Memcached service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Memcached service.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Memcached release of this instance. For convenience, please use gscloud to get the list of available Memcached service releases.
	// The Memcached release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Memcached service releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Memcached service.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// MemcachedSpec defines the desired state of Memcached
type MemcachedSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MemcachedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MemcachedInitParameters `json:"initProvider,omitempty"`
}

// MemcachedStatus defines the observed state of Memcached.
type MemcachedStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MemcachedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Memcached is the Schema for the Memcacheds API. Manage a Memcached service in gridscale
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gridscale}
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   MemcachedSpec   `json:"spec"`
	Status MemcachedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MemcachedList contains a list of Memcacheds
type MemcachedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Memcached `json:"items"`
}

// Repository type metadata.
var (
	Memcached_Kind             = "Memcached"
	Memcached_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Memcached_Kind}.String()
	Memcached_KindAPIVersion   = Memcached_Kind + "." + CRDGroupVersion.String()
	Memcached_GroupVersionKind = CRDGroupVersion.WithKind(Memcached_Kind)
)

func init() {
	SchemeBuilder.Register(&Memcached{}, &MemcachedList{})
}
