// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PostgresqlInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of PostgreSQL service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of PostgreSQL service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// Access key used to authenticate against Object Storage server.
	// Access key used to authenticate against Object Storage server.
	PgauditLogAccessKeySecretRef *v1.SecretKeySelector `json:"pgauditLogAccessKeySecretRef,omitempty" tf:"-"`

	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	PgauditLogBucket *string `json:"pgauditLogBucket,omitempty" tf:"pgaudit_log_bucket,omitempty"`

	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated. Default is 5 minutes.
	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated.
	PgauditLogRotationFrequency *float64 `json:"pgauditLogRotationFrequency,omitempty" tf:"pgaudit_log_rotation_frequency,omitempty"`

	// Secret key used to authenticate against Object Storage server.
	// Secret key used to authenticate against Object Storage server.
	PgauditLogSecretKeySecretRef *v1.SecretKeySelector `json:"pgauditLogSecretKeySecretRef,omitempty" tf:"-"`

	// Object Storage server URL the bucket is located on.
	// Object Storage server URL the bucket is located on.
	PgauditLogServerURL *string `json:"pgauditLogServerUrl,omitempty" tf:"pgaudit_log_server_url,omitempty"`

	// The PostgreSQL release of this instance. For convenience, please use gscloud to get the list of available PostgreSQL service releases.
	// The PostgreSQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available PostgreSQL service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PostgreSQL service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type PostgresqlListenPortInitParameters struct {
}

type PostgresqlListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type PostgresqlListenPortParameters struct {
}

type PostgresqlObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this PostgreSQL service accepts connections.
	// The port numbers where this PostgreSQL service accepts connections.
	ListenPort []PostgresqlListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of PostgreSQL service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of PostgreSQL service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	PgauditLogBucket *string `json:"pgauditLogBucket,omitempty" tf:"pgaudit_log_bucket,omitempty"`

	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated. Default is 5 minutes.
	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated.
	PgauditLogRotationFrequency *float64 `json:"pgauditLogRotationFrequency,omitempty" tf:"pgaudit_log_rotation_frequency,omitempty"`

	// Object Storage server URL the bucket is located on.
	// Object Storage server URL the bucket is located on.
	PgauditLogServerURL *string `json:"pgauditLogServerUrl,omitempty" tf:"pgaudit_log_server_url,omitempty"`

	// The PostgreSQL release of this instance. For convenience, please use gscloud to get the list of available PostgreSQL service releases.
	// The PostgreSQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available PostgreSQL service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PostgreSQL service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that PostgreSQL service uses.
	// PaaS service template that PostgreSQL service uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of PostgreSQL service.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that PostgreSQL service is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type PostgresqlParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and max_core_count.
	// Maximum CPU core count. The PostgreSQL instance's CPU core count will be autoscaled based on the workload. The number of cores stays between 1 and `max_core_count`.
	// +kubebuilder:validation:Optional
	MaxCoreCount *float64 `json:"maxCoreCount,omitempty" tf:"max_core_count,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Performance class of PostgreSQL service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of PostgreSQL service.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// Access key used to authenticate against Object Storage server.
	// Access key used to authenticate against Object Storage server.
	// +kubebuilder:validation:Optional
	PgauditLogAccessKeySecretRef *v1.SecretKeySelector `json:"pgauditLogAccessKeySecretRef,omitempty" tf:"-"`

	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	// Object Storage bucket to upload audit logs to. For pgAudit to be enabled these additional parameters need to be configured: pgaudit_log_server_url, pgaudit_log_access_key, pgaudit_log_secret_key.
	// +kubebuilder:validation:Optional
	PgauditLogBucket *string `json:"pgauditLogBucket,omitempty" tf:"pgaudit_log_bucket,omitempty"`

	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated. Default is 5 minutes.
	// Rotation (in minutes) for audit logs. Logs are uploaded to Object Storage once rotated.
	// +kubebuilder:validation:Optional
	PgauditLogRotationFrequency *float64 `json:"pgauditLogRotationFrequency,omitempty" tf:"pgaudit_log_rotation_frequency,omitempty"`

	// Secret key used to authenticate against Object Storage server.
	// Secret key used to authenticate against Object Storage server.
	// +kubebuilder:validation:Optional
	PgauditLogSecretKeySecretRef *v1.SecretKeySelector `json:"pgauditLogSecretKeySecretRef,omitempty" tf:"-"`

	// Object Storage server URL the bucket is located on.
	// Object Storage server URL the bucket is located on.
	// +kubebuilder:validation:Optional
	PgauditLogServerURL *string `json:"pgauditLogServerUrl,omitempty" tf:"pgaudit_log_server_url,omitempty"`

	// The PostgreSQL release of this instance. For convenience, please use gscloud to get the list of available PostgreSQL service releases.
	// The PostgreSQL release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available PostgreSQL service releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PostgreSQL service.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// PostgresqlSpec defines the desired state of Postgresql
type PostgresqlSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PostgresqlParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PostgresqlInitParameters `json:"initProvider,omitempty"`
}

// PostgresqlStatus defines the observed state of Postgresql.
type PostgresqlStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PostgresqlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Postgresql is the Schema for the Postgresqls API. Manage a PostgreSQL service in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gridscale}
type Postgresql struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   PostgresqlSpec   `json:"spec"`
	Status PostgresqlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PostgresqlList contains a list of Postgresqls
type PostgresqlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Postgresql `json:"items"`
}

// Repository type metadata.
var (
	Postgresql_Kind             = "Postgresql"
	Postgresql_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Postgresql_Kind}.String()
	Postgresql_KindAPIVersion   = Postgresql_Kind + "." + CRDGroupVersion.String()
	Postgresql_GroupVersionKind = CRDGroupVersion.WithKind(Postgresql_Kind)
)

func init() {
	SchemeBuilder.Register(&Postgresql{}, &PostgresqlList{})
}
