// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/PlatformRelay/provider-gridscale/apis/cluster/gridscale/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Clone.
func (mg *Clone) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceStorageID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SourceStorageIDRef,
		Selector:     mg.Spec.ForProvider.SourceStorageIDSelector,
		To: reference.To{
			List:    &v1alpha1.StorageList{},
			Managed: &v1alpha1.Storage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceStorageID")
	}
	mg.Spec.ForProvider.SourceStorageID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceStorageIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceStorageID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SourceStorageIDRef,
		Selector:     mg.Spec.InitProvider.SourceStorageIDSelector,
		To: reference.To{
			List:    &v1alpha1.StorageList{},
			Managed: &v1alpha1.Storage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SourceStorageID")
	}
	mg.Spec.InitProvider.SourceStorageID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourceStorageIDRef = rsp.ResolvedReference

	return nil
}
