// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PaasInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/namespaced/gridscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.NamespacedReference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.NamespacedSelector `json:"networkUuidSelector,omitempty" tf:"-"`

	// See Argument Reference above.
	// Parameter for PaaS service
	Parameter []ParameterInitParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// A list of service resource limits..
	// Resource for PaaS service
	ResourceLimit []ResourceLimitInitParameters `json:"resourceLimit,omitempty" tf:"resource_limit,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PaaS service
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template used to create the service.
	// Template that PaaS service uses
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`
}

type PaasListenPortInitParameters struct {
}

type PaasListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type PaasListenPortParameters struct {
}

type PaasObservation struct {

	// Time of the last change.
	// Time of the last change
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Time of the creation.
	// Time of the creation
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Current price of PaaS service.
	// Current price of PaaS service
	CurrentPrice *float64 `json:"currentPrice,omitempty" tf:"current_price,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Ports that PaaS service listens to.
	// Ports that PaaS service listens to
	ListenPort []PaasListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// See Argument Reference above.
	// Parameter for PaaS service
	Parameter []ParameterObservation `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// A list of service resource limits..
	// Resource for PaaS service
	ResourceLimit []ResourceLimitObservation `json:"resourceLimit,omitempty" tf:"resource_limit,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PaaS service
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// The template used to create the service.
	// Template that PaaS service uses
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Template that PaaS service uses.
	// Template that PaaS service uses.
	ServiceTemplateUUIDComputed *string `json:"serviceTemplateUuidComputed,omitempty" tf:"service_template_uuid_computed,omitempty"`

	// Current status of PaaS service.
	// Current status of PaaS service
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that PaaS service is in use
	UsageInMinute *float64 `json:"usageInMinute,omitempty" tf:"usage_in_minute,omitempty"`
}

type PaasParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +crossplane:generate:reference:type=github.com/PlatformRelay/provider-gridscale/apis/namespaced/gridscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.NamespacedReference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in gridscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.NamespacedSelector `json:"networkUuidSelector,omitempty" tf:"-"`

	// See Argument Reference above.
	// Parameter for PaaS service
	// +kubebuilder:validation:Optional
	Parameter []ParameterParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// A list of service resource limits..
	// Resource for PaaS service
	// +kubebuilder:validation:Optional
	ResourceLimit []ResourceLimitParameters `json:"resourceLimit,omitempty" tf:"resource_limit,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to PaaS service
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template used to create the service.
	// Template that PaaS service uses
	// +kubebuilder:validation:Optional
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`
}

type ParameterInitParameters struct {

	// Name of parameter.
	Param *string `json:"param,omitempty" tf:"param,omitempty"`

	// Primitive type of the parameter: bool, int (better use float for int case), float, string.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the corresponding parameter.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterObservation struct {

	// Name of parameter.
	Param *string `json:"param,omitempty" tf:"param,omitempty"`

	// Primitive type of the parameter: bool, int (better use float for int case), float, string.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the corresponding parameter.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterParameters struct {

	// Name of parameter.
	// +kubebuilder:validation:Optional
	Param *string `json:"param" tf:"param,omitempty"`

	// Primitive type of the parameter: bool, int (better use float for int case), float, string.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// Value of the corresponding parameter.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ResourceLimitInitParameters struct {

	// The maximum number of the specific resource your service can use.
	Limit *float64 `json:"limit,omitempty" tf:"limit,omitempty"`

	// The name of the resource you would like to cap.
	Resource *string `json:"resource,omitempty" tf:"resource,omitempty"`
}

type ResourceLimitObservation struct {

	// The maximum number of the specific resource your service can use.
	Limit *float64 `json:"limit,omitempty" tf:"limit,omitempty"`

	// The name of the resource you would like to cap.
	Resource *string `json:"resource,omitempty" tf:"resource,omitempty"`
}

type ResourceLimitParameters struct {

	// The maximum number of the specific resource your service can use.
	// +kubebuilder:validation:Optional
	Limit *float64 `json:"limit" tf:"limit,omitempty"`

	// The name of the resource you would like to cap.
	// +kubebuilder:validation:Optional
	Resource *string `json:"resource" tf:"resource,omitempty"`
}

// PaasSpec defines the desired state of Paas
type PaasSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PaasParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PaasInitParameters `json:"initProvider,omitempty"`
}

// PaasStatus defines the observed state of Paas.
type PaasStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PaasObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Paas is the Schema for the Paass API. Manages a PaaS in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type Paas struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceTemplateUuid) || (has(self.initProvider) && has(self.initProvider.serviceTemplateUuid))",message="spec.forProvider.serviceTemplateUuid is a required parameter"
	Spec   PaasSpec   `json:"spec"`
	Status PaasStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PaasList contains a list of Paass
type PaasList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Paas `json:"items"`
}

// Repository type metadata.
var (
	Paas_Kind             = "Paas"
	Paas_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Paas_Kind}.String()
	Paas_KindAPIVersion   = Paas_Kind + "." + CRDGroupVersion.String()
	Paas_GroupVersionKind = CRDGroupVersion.WithKind(Paas_Kind)
)

func init() {
	SchemeBuilder.Register(&Paas{}, &PaasList{})
}
