// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type S3BackupInitParameters struct {

	// Access key used to authenticate against Object Storage server.
	// Access key used to authenticate against Object Storage server.
	BackupAccessKeySecretRef v1.LocalSecretKeySelector `json:"backupAccessKeySecretRef" tf:"-"`

	// Object Storage bucket to upload backups to and restore backups from.
	// Object Storage bucket to upload backups to and restore backups from.
	BackupBucket *string `json:"backupBucket,omitempty" tf:"backup_bucket,omitempty"`

	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	BackupRetention *float64 `json:"backupRetention,omitempty" tf:"backup_retention,omitempty"`

	// Secret key used to authenticate against Object Storage server.
	// Secret key used to authenticate against Object Storage server.
	BackupSecretKeySecretRef v1.LocalSecretKeySelector `json:"backupSecretKeySecretRef" tf:"-"`

	// Object Storage server URL the bucket is located on. Note: Currently, only object storage host "https://gos3.io/" is supported.
	// Object Storage server URL the bucket is located on.
	BackupServerURL *string `json:"backupServerUrl,omitempty" tf:"backup_server_url,omitempty"`
}

type S3BackupObservation struct {

	// Object Storage bucket to upload backups to and restore backups from.
	// Object Storage bucket to upload backups to and restore backups from.
	BackupBucket *string `json:"backupBucket,omitempty" tf:"backup_bucket,omitempty"`

	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	BackupRetention *float64 `json:"backupRetention,omitempty" tf:"backup_retention,omitempty"`

	// Object Storage server URL the bucket is located on. Note: Currently, only object storage host "https://gos3.io/" is supported.
	// Object Storage server URL the bucket is located on.
	BackupServerURL *string `json:"backupServerUrl,omitempty" tf:"backup_server_url,omitempty"`
}

type S3BackupParameters struct {

	// Access key used to authenticate against Object Storage server.
	// Access key used to authenticate against Object Storage server.
	// +kubebuilder:validation:Optional
	BackupAccessKeySecretRef v1.LocalSecretKeySelector `json:"backupAccessKeySecretRef" tf:"-"`

	// Object Storage bucket to upload backups to and restore backups from.
	// Object Storage bucket to upload backups to and restore backups from.
	// +kubebuilder:validation:Optional
	BackupBucket *string `json:"backupBucket" tf:"backup_bucket,omitempty"`

	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	// Retention (in seconds) for local originals of backups. (0 for immediate removal once uploaded to Object Storage (default), higher values for delayed removal after the given time and once uploaded to Object Storage).
	// +kubebuilder:validation:Optional
	BackupRetention *float64 `json:"backupRetention,omitempty" tf:"backup_retention,omitempty"`

	// Secret key used to authenticate against Object Storage server.
	// Secret key used to authenticate against Object Storage server.
	// +kubebuilder:validation:Optional
	BackupSecretKeySecretRef v1.LocalSecretKeySelector `json:"backupSecretKeySecretRef" tf:"-"`

	// Object Storage server URL the bucket is located on. Note: Currently, only object storage host "https://gos3.io/" is supported.
	// Object Storage server URL the bucket is located on.
	// +kubebuilder:validation:Optional
	BackupServerURL *string `json:"backupServerUrl,omitempty" tf:"backup_server_url,omitempty"`
}

type SqlserverInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of MS SQL server service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MS SQL Server.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MS SQL server release of this instance. For convenience, please use gscloud to get the list of available MS SQL server service releases.
	// The MS SQL Server release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MS SQL Server releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// Allow backup/restore MS SQL server to/from a S3 bucket.
	// Allow backup/restore MS SQL server to/from a S3 bucket.
	S3Backup []S3BackupInitParameters `json:"s3Backup,omitempty" tf:"s3_backup,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MS SQL Server.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type SqlserverListenPortInitParameters struct {
}

type SqlserverListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type SqlserverListenPortParameters struct {
}

type SqlserverObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this MS SQL server service accepts connections.
	// The port numbers where this MS SQL Server accepts connections.
	ListenPort []SqlserverListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of MS SQL server service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MS SQL Server.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MS SQL server release of this instance. For convenience, please use gscloud to get the list of available MS SQL server service releases.
	// The MS SQL Server release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MS SQL Server releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// Allow backup/restore MS SQL server to/from a S3 bucket.
	// Allow backup/restore MS SQL server to/from a S3 bucket.
	S3Backup []S3BackupObservation `json:"s3Backup,omitempty" tf:"s3_backup,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MS SQL Server.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that MS SQL server service uses.
	// PaaS service template that MS SQL Server uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of MS SQL Server.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that MS SQL Server is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type SqlserverParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of MS SQL server service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of MS SQL Server.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The MS SQL server release of this instance. For convenience, please use gscloud to get the list of available MS SQL server service releases.
	// The MS SQL Server release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available MS SQL Server releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// Allow backup/restore MS SQL server to/from a S3 bucket.
	// Allow backup/restore MS SQL server to/from a S3 bucket.
	// +kubebuilder:validation:Optional
	S3Backup []S3BackupParameters `json:"s3Backup,omitempty" tf:"s3_backup,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to MS SQL Server.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// SqlserverSpec defines the desired state of Sqlserver
type SqlserverSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SqlserverParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SqlserverInitParameters `json:"initProvider,omitempty"`
}

// SqlserverStatus defines the observed state of Sqlserver.
type SqlserverStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SqlserverObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Sqlserver is the Schema for the Sqlservers API. Manage a MS SQL server service in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type Sqlserver struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   SqlserverSpec   `json:"spec"`
	Status SqlserverStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SqlserverList contains a list of Sqlservers
type SqlserverList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Sqlserver `json:"items"`
}

// Repository type metadata.
var (
	Sqlserver_Kind             = "Sqlserver"
	Sqlserver_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Sqlserver_Kind}.String()
	Sqlserver_KindAPIVersion   = Sqlserver_Kind + "." + CRDGroupVersion.String()
	Sqlserver_GroupVersionKind = CRDGroupVersion.WithKind(Sqlserver_Kind)
)

func init() {
	SchemeBuilder.Register(&Sqlserver{}, &SqlserverList{})
}
