apiVersion: gridscale.gridscale.m.platformrelay.io/v1alpha1
kind: Template
metadata:
  name: observe-template
  namespace: crossplane-system
  annotations:
    # Set external-name to the UUID of the existing gridscale resource to observe.
    crossplane.io/external-name: "<replace-with-uuid>"
spec:
  managementPolicies:
    - Observe
  providerConfigRef:
    name: default
  forProvider: {}
