// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type StoreInitParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of Redis store service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Redis store service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Redis store release of this instance. For convenience, please use gscloud to get the list of available Redis store service releases.
	// The RedisStore release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Redis store service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Redis store service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

type StoreListenPortInitParameters struct {
}

type StoreListenPortObservation struct {

	// Host address.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type StoreListenPortParameters struct {
}

type StoreObservation struct {

	// Time of the last change.
	// Time of the last change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Date time this service has been created.
	// Date time this service has been created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The port numbers where this Redis store service accepts connections.
	// The port numbers where this Redis store service accepts connections.
	ListenPort []StoreListenPortObservation `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of Redis store service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Redis store service.
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Redis store release of this instance. For convenience, please use gscloud to get the list of available Redis store service releases.
	// The RedisStore release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Redis store service releases.
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Redis store service.
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`

	// The template service's category used to create the service.
	// The template service's category used to create the service.
	ServiceTemplateCategory *string `json:"serviceTemplateCategory,omitempty" tf:"service_template_category,omitempty"`

	// PaaS service template that Redis store service uses.
	// PaaS service template that Redis store service uses.
	ServiceTemplateUUID *string `json:"serviceTemplateUuid,omitempty" tf:"service_template_uuid,omitempty"`

	// Current status of PaaS service.
	// Current status of Redis store service.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of minutes that PaaS service is in use.
	// Number of minutes that Redis store service is in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type StoreParameters struct {

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the network that the service is attached to.
	// The UUID of the network that the service is attached to.
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Performance class of Redis store service. Available performance classes at the time of writing: standard, high, insane, ultra.
	// Performance class of Redis store service.
	// +kubebuilder:validation:Optional
	PerformanceClass *string `json:"performanceClass,omitempty" tf:"performance_class,omitempty"`

	// The Redis store release of this instance. For convenience, please use gscloud to get the list of available Redis store service releases.
	// The RedisStore release of this instance.\n
	// For convenience, please use gscloud https://github.com/gridscale/gscloud to get the list of available Redis store service releases.
	// +kubebuilder:validation:Optional
	Release *string `json:"release,omitempty" tf:"release,omitempty"`

	// DEPRECATED  The UUID of the security zone that the service is attached to.
	// Security zone UUID linked to Redis store service.
	// +kubebuilder:validation:Optional
	SecurityZoneUUID *string `json:"securityZoneUuid,omitempty" tf:"security_zone_uuid,omitempty"`
}

// StoreSpec defines the desired state of Store
type StoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            StoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StoreInitParameters `json:"initProvider,omitempty"`
}

// StoreStatus defines the observed state of Store.
type StoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Store is the Schema for the Stores API. Manage a Redis store service in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type Store struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.performanceClass) || (has(self.initProvider) && has(self.initProvider.performanceClass))",message="spec.forProvider.performanceClass is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.release) || (has(self.initProvider) && has(self.initProvider.release))",message="spec.forProvider.release is a required parameter"
	Spec   StoreSpec   `json:"spec"`
	Status StoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StoreList contains a list of Stores
type StoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Store `json:"items"`
}

// Repository type metadata.
var (
	Store_Kind             = "Store"
	Store_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Store_Kind}.String()
	Store_KindAPIVersion   = Store_Kind + "." + CRDGroupVersion.String()
	Store_GroupVersionKind = CRDGroupVersion.WithKind(Store_Kind)
)

func init() {
	SchemeBuilder.Register(&Store{}, &StoreList{})
}
