//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenPortInitParameters) DeepCopyInto(out *ListenPortInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenPortInitParameters.
func (in *ListenPortInitParameters) DeepCopy() *ListenPortInitParameters {
	if in == nil {
		return nil
	}
	out := new(ListenPortInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenPortObservation) DeepCopyInto(out *ListenPortObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenPortObservation.
func (in *ListenPortObservation) DeepCopy() *ListenPortObservation {
	if in == nil {
		return nil
	}
	out := new(ListenPortObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenPortParameters) DeepCopyInto(out *ListenPortParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenPortParameters.
func (in *ListenPortParameters) DeepCopy() *ListenPortParameters {
	if in == nil {
		return nil
	}
	out := new(ListenPortParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8) DeepCopyInto(out *MySQL8) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8.
func (in *MySQL8) DeepCopy() *MySQL8 {
	if in == nil {
		return nil
	}
	out := new(MySQL8)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySQL8) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8InitParameters) DeepCopyInto(out *MySQL8InitParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxCoreCount != nil {
		in, out := &in.MaxCoreCount, &out.MaxCoreCount
		*out = new(float64)
		**out = **in
	}
	if in.MySQLDefaultTimeZone != nil {
		in, out := &in.MySQLDefaultTimeZone, &out.MySQLDefaultTimeZone
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxAllowedPacket != nil {
		in, out := &in.MySQLMaxAllowedPacket, &out.MySQLMaxAllowedPacket
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxConnections != nil {
		in, out := &in.MySQLMaxConnections, &out.MySQLMaxConnections
		*out = new(float64)
		**out = **in
	}
	if in.MySQLSQLMode != nil {
		in, out := &in.MySQLSQLMode, &out.MySQLSQLMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkUUID != nil {
		in, out := &in.NetworkUUID, &out.NetworkUUID
		*out = new(string)
		**out = **in
	}
	if in.PerformanceClass != nil {
		in, out := &in.PerformanceClass, &out.PerformanceClass
		*out = new(string)
		**out = **in
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(string)
		**out = **in
	}
	if in.SecurityZoneUUID != nil {
		in, out := &in.SecurityZoneUUID, &out.SecurityZoneUUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8InitParameters.
func (in *MySQL8InitParameters) DeepCopy() *MySQL8InitParameters {
	if in == nil {
		return nil
	}
	out := new(MySQL8InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8List) DeepCopyInto(out *MySQL8List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySQL8, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8List.
func (in *MySQL8List) DeepCopy() *MySQL8List {
	if in == nil {
		return nil
	}
	out := new(MySQL8List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySQL8List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8Observation) DeepCopyInto(out *MySQL8Observation) {
	*out = *in
	if in.ChangeTime != nil {
		in, out := &in.ChangeTime, &out.ChangeTime
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = make([]ListenPortObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxCoreCount != nil {
		in, out := &in.MaxCoreCount, &out.MaxCoreCount
		*out = new(float64)
		**out = **in
	}
	if in.MySQLDefaultTimeZone != nil {
		in, out := &in.MySQLDefaultTimeZone, &out.MySQLDefaultTimeZone
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxAllowedPacket != nil {
		in, out := &in.MySQLMaxAllowedPacket, &out.MySQLMaxAllowedPacket
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxConnections != nil {
		in, out := &in.MySQLMaxConnections, &out.MySQLMaxConnections
		*out = new(float64)
		**out = **in
	}
	if in.MySQLSQLMode != nil {
		in, out := &in.MySQLSQLMode, &out.MySQLSQLMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkUUID != nil {
		in, out := &in.NetworkUUID, &out.NetworkUUID
		*out = new(string)
		**out = **in
	}
	if in.PerformanceClass != nil {
		in, out := &in.PerformanceClass, &out.PerformanceClass
		*out = new(string)
		**out = **in
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(string)
		**out = **in
	}
	if in.SecurityZoneUUID != nil {
		in, out := &in.SecurityZoneUUID, &out.SecurityZoneUUID
		*out = new(string)
		**out = **in
	}
	if in.ServiceTemplateCategory != nil {
		in, out := &in.ServiceTemplateCategory, &out.ServiceTemplateCategory
		*out = new(string)
		**out = **in
	}
	if in.ServiceTemplateUUID != nil {
		in, out := &in.ServiceTemplateUUID, &out.ServiceTemplateUUID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UsageInMinutes != nil {
		in, out := &in.UsageInMinutes, &out.UsageInMinutes
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8Observation.
func (in *MySQL8Observation) DeepCopy() *MySQL8Observation {
	if in == nil {
		return nil
	}
	out := new(MySQL8Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8Parameters) DeepCopyInto(out *MySQL8Parameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxCoreCount != nil {
		in, out := &in.MaxCoreCount, &out.MaxCoreCount
		*out = new(float64)
		**out = **in
	}
	if in.MySQLDefaultTimeZone != nil {
		in, out := &in.MySQLDefaultTimeZone, &out.MySQLDefaultTimeZone
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxAllowedPacket != nil {
		in, out := &in.MySQLMaxAllowedPacket, &out.MySQLMaxAllowedPacket
		*out = new(string)
		**out = **in
	}
	if in.MySQLMaxConnections != nil {
		in, out := &in.MySQLMaxConnections, &out.MySQLMaxConnections
		*out = new(float64)
		**out = **in
	}
	if in.MySQLSQLMode != nil {
		in, out := &in.MySQLSQLMode, &out.MySQLSQLMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkUUID != nil {
		in, out := &in.NetworkUUID, &out.NetworkUUID
		*out = new(string)
		**out = **in
	}
	if in.PerformanceClass != nil {
		in, out := &in.PerformanceClass, &out.PerformanceClass
		*out = new(string)
		**out = **in
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(string)
		**out = **in
	}
	if in.SecurityZoneUUID != nil {
		in, out := &in.SecurityZoneUUID, &out.SecurityZoneUUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8Parameters.
func (in *MySQL8Parameters) DeepCopy() *MySQL8Parameters {
	if in == nil {
		return nil
	}
	out := new(MySQL8Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8Spec) DeepCopyInto(out *MySQL8Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8Spec.
func (in *MySQL8Spec) DeepCopy() *MySQL8Spec {
	if in == nil {
		return nil
	}
	out := new(MySQL8Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQL8Status) DeepCopyInto(out *MySQL8Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQL8Status.
func (in *MySQL8Status) DeepCopy() *MySQL8Status {
	if in == nil {
		return nil
	}
	out := new(MySQL8Status)
	in.DeepCopyInto(out)
	return out
}
