// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/PlatformRelay/provider-gridscale/apis/namespaced/gridscale/v1alpha1"
	v1alpha1marketplace "github.com/PlatformRelay/provider-gridscale/apis/namespaced/marketplace/v1alpha1"
	v1alpha1mysql8 "github.com/PlatformRelay/provider-gridscale/apis/namespaced/mysql8/v1alpha1"
	v1alpha1object "github.com/PlatformRelay/provider-gridscale/apis/namespaced/object/v1alpha1"
	v1alpha1paas "github.com/PlatformRelay/provider-gridscale/apis/namespaced/paas/v1alpha1"
	v1alpha1redis "github.com/PlatformRelay/provider-gridscale/apis/namespaced/redis/v1alpha1"
	v1alpha1ssl "github.com/PlatformRelay/provider-gridscale/apis/namespaced/ssl/v1alpha1"
	v1alpha1storage "github.com/PlatformRelay/provider-gridscale/apis/namespaced/storage/v1alpha1"
	v1alpha1namespaced "github.com/PlatformRelay/provider-gridscale/apis/namespaced/v1alpha1"
	v1beta1 "github.com/PlatformRelay/provider-gridscale/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1marketplace.SchemeBuilder.AddToScheme,
		v1alpha1mysql8.SchemeBuilder.AddToScheme,
		v1alpha1object.SchemeBuilder.AddToScheme,
		v1alpha1paas.SchemeBuilder.AddToScheme,
		v1alpha1redis.SchemeBuilder.AddToScheme,
		v1alpha1ssl.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
