// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SecurityzoneInitParameters struct {

	// List of labels.
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The location this object is placed.
	// The location this object is placed.
	LocationUUID *string `json:"locationUuid,omitempty" tf:"location_uuid,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecurityzoneObservation struct {

	// Defines the date and time of the last object change.
	// Defines the date and time of the last object change
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// Defines the date and time the object was initially created.
	// Defines the date and time the object was initially created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The UUID of the security zone.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels.
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the location's country.
	// The human-readable name of the location
	LocationCountry *string `json:"locationCountry,omitempty" tf:"location_country,omitempty"`

	// Uses IATA airport code, which works as a location identifier.
	// Uses IATA airport code, which works as a location identifier
	LocationIata *string `json:"locationIata,omitempty" tf:"location_iata,omitempty"`

	// The human-readable name of the location.
	// The human-readable name of the location
	LocationName *string `json:"locationName,omitempty" tf:"location_name,omitempty"`

	// The location this object is placed.
	// The location this object is placed.
	LocationUUID *string `json:"locationUuid,omitempty" tf:"location_uuid,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of PaaS services' UUIDs relating to the security zone.
	// List of PaaS services' UUIDs relating to the security zone
	// +listType=set
	Relations []*string `json:"relations,omitempty" tf:"relations,omitempty"`

	// Status indicates the status of the object.
	// Status indicates the status of the object
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type SecurityzoneParameters struct {

	// List of labels.
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The location this object is placed.
	// The location this object is placed.
	// +kubebuilder:validation:Optional
	LocationUUID *string `json:"locationUuid,omitempty" tf:"location_uuid,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// SecurityzoneSpec defines the desired state of Securityzone
type SecurityzoneSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecurityzoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityzoneInitParameters `json:"initProvider,omitempty"`
}

// SecurityzoneStatus defines the observed state of Securityzone.
type SecurityzoneStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityzoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Securityzone is the Schema for the Securityzones API. Manages a security zone in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type Securityzone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SecurityzoneSpec   `json:"spec"`
	Status SecurityzoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityzoneList contains a list of Securityzones
type SecurityzoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Securityzone `json:"items"`
}

// Repository type metadata.
var (
	Securityzone_Kind             = "Securityzone"
	Securityzone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Securityzone_Kind}.String()
	Securityzone_KindAPIVersion   = Securityzone_Kind + "." + CRDGroupVersion.String()
	Securityzone_GroupVersionKind = CRDGroupVersion.WithKind(Securityzone_Kind)
)

func init() {
	SchemeBuilder.Register(&Securityzone{}, &SecurityzoneList{})
}
