apiVersion: gridscale.gridscale.m.platformrelay.io/v1alpha1
kind: Loadbalancer
metadata:
  annotations:
    meta.upbound.io/example-id: gridscale/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    algorithm: leastconn
    backendServer:
    - hostSelector:
        matchLabels:
          testing.upbound.io/example-name: server
      weight: 100
    forwardingRule:
    - listenPort: 80
      mode: http
      targetPort: 80
    labels: []
    listenIpv4UuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
    listenIpv6UuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
    name: test-lb
    redirectHttpToHttps: false
    timeouts:
    - create: 10m
