// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type StorageImportInitParameters struct {

	// The default value is inherited from the source storage instance. A desired capacity is possible. Required (integer - minimum: 1 - maximum: 4096).
	// The capacity of a storage in GB.
	Capacity *float64 `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the storage backup that will be used to create a new storage from.
	// ID of the storage backup that will be used to create a new storage from.
	StorageBackupID *string `json:"storageBackupId,omitempty" tf:"storage_backup_id,omitempty"`

	// The default value is inherited from the source storage instance. A desired storage type is possible. (one of storage, storage_high, storage_insane).
	// (one of storage, storage_high, storage_insane)
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

type StorageImportObservation struct {

	// The default value is inherited from the source storage instance. A desired capacity is possible. Required (integer - minimum: 1 - maximum: 4096).
	// The capacity of a storage in GB.
	Capacity *float64 `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// Defines the date and time of the last object change.
	// Defines the date and time of the last object change.
	ChangeTime *string `json:"changeTime,omitempty" tf:"change_time,omitempty"`

	// The time the object was created.
	// Defines the date and time the object was initially created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The price for the current period since the last bill.
	CurrentPrice *float64 `json:"currentPrice,omitempty" tf:"current_price,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Indicates the UUID of the last used template on this storage (inherited from snapshots).
	LastUsedTemplate *string `json:"lastUsedTemplate,omitempty" tf:"last_used_template,omitempty"`

	// If a template has been used that requires a license key (e.g. Windows Servers) this shows the product_no of the license (see the /prices endpoint for more details).
	// If a template has been used that requires a license key (e.g. Windows Servers) this shows the product_no of the license (see the /prices endpoint for more details).
	LicenseProductNo *float64 `json:"licenseProductNo,omitempty" tf:"license_product_no,omitempty"`

	// Two digit country code (ISO 3166-2) of the location where this object is placed.
	// Two digit country code (ISO 3166-2) of the location where this object is placed.
	LocationCountry *string `json:"locationCountry,omitempty" tf:"location_country,omitempty"`

	// Uses IATA airport code, which works as a location identifier.
	// Uses IATA airport code, which works as a location identifier.
	LocationIata *string `json:"locationIata,omitempty" tf:"location_iata,omitempty"`

	// The location name.
	// The human-readable name of the location. It supports the full UTF-8 character set, with a maximum of 64 characters.
	LocationName *string `json:"locationName,omitempty" tf:"location_name,omitempty"`

	// The location this resource is placed. The location of a resource is determined by it's project.
	// Identifies the data center this object belongs to.
	LocationUUID *string `json:"locationUuid,omitempty" tf:"location_uuid,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// status indicates the status of the object.
	// status indicates the status of the object.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// ID of the storage backup that will be used to create a new storage from.
	// ID of the storage backup that will be used to create a new storage from.
	StorageBackupID *string `json:"storageBackupId,omitempty" tf:"storage_backup_id,omitempty"`

	// The default value is inherited from the source storage instance. A desired storage type is possible. (one of storage, storage_high, storage_insane).
	// (one of storage, storage_high, storage_insane)
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`

	// The amount of minutes the IP address has been in use.
	UsageInMinutes *float64 `json:"usageInMinutes,omitempty" tf:"usage_in_minutes,omitempty"`
}

type StorageImportParameters struct {

	// The default value is inherited from the source storage instance. A desired capacity is possible. Required (integer - minimum: 1 - maximum: 4096).
	// The capacity of a storage in GB.
	// +kubebuilder:validation:Optional
	Capacity *float64 `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// List of labels in the format [ "label1", "label2" ].
	// List of labels.
	// +kubebuilder:validation:Optional
	// +listType=set
	Labels []*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// The human-readable name of the object. It supports the full UTF-8 character set, with a maximum of 64 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the storage backup that will be used to create a new storage from.
	// ID of the storage backup that will be used to create a new storage from.
	// +kubebuilder:validation:Optional
	StorageBackupID *string `json:"storageBackupId,omitempty" tf:"storage_backup_id,omitempty"`

	// The default value is inherited from the source storage instance. A desired storage type is possible. (one of storage, storage_high, storage_insane).
	// (one of storage, storage_high, storage_insane)
	// +kubebuilder:validation:Optional
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`
}

// StorageImportSpec defines the desired state of StorageImport
type StorageImportSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            StorageImportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageImportInitParameters `json:"initProvider,omitempty"`
}

// StorageImportStatus defines the observed state of StorageImport.
type StorageImportStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageImportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageImport is the Schema for the StorageImports API. Make a clone of an existing storage instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type StorageImport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storageBackupId) || (has(self.initProvider) && has(self.initProvider.storageBackupId))",message="spec.forProvider.storageBackupId is a required parameter"
	Spec   StorageImportSpec   `json:"spec"`
	Status StorageImportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageImportList contains a list of StorageImports
type StorageImportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageImport `json:"items"`
}

// Repository type metadata.
var (
	StorageImport_Kind             = "StorageImport"
	StorageImport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageImport_Kind}.String()
	StorageImport_KindAPIVersion   = StorageImport_Kind + "." + CRDGroupVersion.String()
	StorageImport_GroupVersionKind = CRDGroupVersion.WithKind(StorageImport_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageImport{}, &StorageImportList{})
}
