// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LifecycleRuleInitParameters struct {

	// Whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Number of days after which objects are deleted. Default: 365.
	ExpirationDays *float64 `json:"expirationDays,omitempty" tf:"expiration_days,omitempty"`

	// Unique identifier for the rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Number of days after which incomplete multipart uploads are deleted. Default: 3.
	IncompleteUploadExpirationDays *float64 `json:"incompleteUploadExpirationDays,omitempty" tf:"incomplete_upload_expiration_days,omitempty"`

	// Number of days after which noncurrent object versions are deleted. Default: 365.
	NoncurrentVersionExpirationDays *float64 `json:"noncurrentVersionExpirationDays,omitempty" tf:"noncurrent_version_expiration_days,omitempty"`

	// Object key prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type LifecycleRuleObservation struct {

	// Whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Number of days after which objects are deleted. Default: 365.
	ExpirationDays *float64 `json:"expirationDays,omitempty" tf:"expiration_days,omitempty"`

	// Unique identifier for the rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Number of days after which incomplete multipart uploads are deleted. Default: 3.
	IncompleteUploadExpirationDays *float64 `json:"incompleteUploadExpirationDays,omitempty" tf:"incomplete_upload_expiration_days,omitempty"`

	// Number of days after which noncurrent object versions are deleted. Default: 365.
	NoncurrentVersionExpirationDays *float64 `json:"noncurrentVersionExpirationDays,omitempty" tf:"noncurrent_version_expiration_days,omitempty"`

	// Object key prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type LifecycleRuleParameters struct {

	// Whether the rule is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// Number of days after which objects are deleted. Default: 365.
	// +kubebuilder:validation:Optional
	ExpirationDays *float64 `json:"expirationDays,omitempty" tf:"expiration_days,omitempty"`

	// Unique identifier for the rule.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// Number of days after which incomplete multipart uploads are deleted. Default: 3.
	// +kubebuilder:validation:Optional
	IncompleteUploadExpirationDays *float64 `json:"incompleteUploadExpirationDays,omitempty" tf:"incomplete_upload_expiration_days,omitempty"`

	// Number of days after which noncurrent object versions are deleted. Default: 365.
	// +kubebuilder:validation:Optional
	NoncurrentVersionExpirationDays *float64 `json:"noncurrentVersionExpirationDays,omitempty" tf:"noncurrent_version_expiration_days,omitempty"`

	// Object key prefix identifying one or more objects to which the rule applies.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type StorageBucketInitParameters struct {

	// Access key.
	// The object storage secret_key.
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// Name of the bucket.
	// The name of the bucket.
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// A list of lifecycle rules for the bucket. Each rule supports the following:
	LifecycleRule []LifecycleRuleInitParameters `json:"lifecycleRule,omitempty" tf:"lifecycle_rule,omitempty"`

	// Host of the s3. Default: "gos3.io".
	// The S3 host.
	S3Host *string `json:"s3Host,omitempty" tf:"s3_host,omitempty"`

	// Secret key.
	// The object storage access_key.
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

type StorageBucketObservation struct {

	// Name of the bucket.
	// The name of the bucket.
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Unique identifier for the rule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of lifecycle rules for the bucket. Each rule supports the following:
	LifecycleRule []LifecycleRuleObservation `json:"lifecycleRule,omitempty" tf:"lifecycle_rule,omitempty"`

	// Host of the s3. Default: "gos3.io".
	// The S3 host.
	S3Host *string `json:"s3Host,omitempty" tf:"s3_host,omitempty"`
}

type StorageBucketParameters struct {

	// Access key.
	// The object storage secret_key.
	// +kubebuilder:validation:Optional
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// Name of the bucket.
	// The name of the bucket.
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// A list of lifecycle rules for the bucket. Each rule supports the following:
	// +kubebuilder:validation:Optional
	LifecycleRule []LifecycleRuleParameters `json:"lifecycleRule,omitempty" tf:"lifecycle_rule,omitempty"`

	// Host of the s3. Default: "gos3.io".
	// The S3 host.
	// +kubebuilder:validation:Optional
	S3Host *string `json:"s3Host,omitempty" tf:"s3_host,omitempty"`

	// Secret key.
	// The object storage access_key.
	// +kubebuilder:validation:Optional
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

// StorageBucketSpec defines the desired state of StorageBucket
type StorageBucketSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            StorageBucketParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageBucketInitParameters `json:"initProvider,omitempty"`
}

// StorageBucketStatus defines the observed state of StorageBucket.
type StorageBucketStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageBucketObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageBucket is the Schema for the StorageBuckets API. Manages an object storage bucket in gridscale.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gridscale}
type StorageBucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accessKeySecretRef)",message="spec.forProvider.accessKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bucketName) || (has(self.initProvider) && has(self.initProvider.bucketName))",message="spec.forProvider.bucketName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretKeySecretRef)",message="spec.forProvider.secretKeySecretRef is a required parameter"
	Spec   StorageBucketSpec   `json:"spec"`
	Status StorageBucketStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageBucketList contains a list of StorageBuckets
type StorageBucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageBucket `json:"items"`
}

// Repository type metadata.
var (
	StorageBucket_Kind             = "StorageBucket"
	StorageBucket_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageBucket_Kind}.String()
	StorageBucket_KindAPIVersion   = StorageBucket_Kind + "." + CRDGroupVersion.String()
	StorageBucket_GroupVersionKind = CRDGroupVersion.WithKind(StorageBucket_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageBucket{}, &StorageBucketList{})
}
