apiVersion: redis.gridscale.m.platformrelay.io/v1alpha1
kind: Store
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1alpha1/store
  labels:
    testing.upbound.io/example-name: terra-redis-store-test
  name: terra-redis-store-test
  namespace: crossplane-system
spec:
  forProvider:
    labels:
    - test
    name: test
    performanceClass: standard
    release: "5.0"
