apiVersion: gridscale.gridscale.platformrelay.io/v1alpha1
kind: IPv4
metadata:
  name: observe-ipv4
  annotations:
    # Set external-name to the UUID of the existing gridscale resource to observe.
    crossplane.io/external-name: "<replace-with-uuid>"
spec:
  managementPolicies:
    - Observe
  providerConfigRef:
    name: default
  forProvider: {}
